on: [push]

jobs:
  deploy_artifact_job:
    runs-on: ubuntu-latest
    name: Deploy the artifact on the DataMiner System job
    steps:
      # To use this action, the repository must be checked out 
      - name: Checkout	
        uses: actions/checkout@v3
      - name: Set up NuGet
        uses: nuget/setup-nuget@v1.1.1      
      - name: NuGet restore solution
        run: nuget restore "AutomationScript.sln" -OutputDirectory ${{ github.workspace }}/packages
      - name: Deploy the artifact on the DataMiner System step
        uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
        id: deploy_artifact_step
        with:
          api-key: ${{ secrets.PCK_LAB }}
          solution-path: './Example/Script.sln'
          artifact-name: 'MyArtifactName'
          version: '1.0.1'
          timeout: '300'
